// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCexvwHuVtcDdmnvb2tOhpEjqBJdWu82qg',
    appId: '1:212773337833:web:f775c493b973179e174e78',
    messagingSenderId: '212773337833',
    projectId: 'lezzetpusulasi-e9525',
    authDomain: 'lezzetpusulasi-e9525.firebaseapp.com',
    storageBucket: 'lezzetpusulasi-e9525.firebasestorage.app',
    measurementId: 'G-FMJ6FGX1FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoMIp6UwwddkwyxPP-ILxxFPu1dxSGWks',
    appId: '1:212773337833:android:e2b8f2b091d3b926174e78',
    messagingSenderId: '212773337833',
    projectId: 'lezzetpusulasi-e9525',
    storageBucket: 'lezzetpusulasi-e9525.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGEGW7y4t37euKxBDDfXLUAIoJFmCQZZ4',
    appId: '1:212773337833:ios:99259c085853e4fb174e78',
    messagingSenderId: '212773337833',
    projectId: 'lezzetpusulasi-e9525',
    storageBucket: 'lezzetpusulasi-e9525.firebasestorage.app',
    iosClientId: '212773337833-5kmu0kh2aak01qpvnf5mrgmqap2pifvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lezzetPusulasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGEGW7y4t37euKxBDDfXLUAIoJFmCQZZ4',
    appId: '1:212773337833:ios:99259c085853e4fb174e78',
    messagingSenderId: '212773337833',
    projectId: 'lezzetpusulasi-e9525',
    storageBucket: 'lezzetpusulasi-e9525.firebasestorage.app',
    iosClientId: '212773337833-5kmu0kh2aak01qpvnf5mrgmqap2pifvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lezzetPusulasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCexvwHuVtcDdmnvb2tOhpEjqBJdWu82qg',
    appId: '1:212773337833:web:4788b3f27df51e24174e78',
    messagingSenderId: '212773337833',
    projectId: 'lezzetpusulasi-e9525',
    authDomain: 'lezzetpusulasi-e9525.firebaseapp.com',
    storageBucket: 'lezzetpusulasi-e9525.firebasestorage.app',
    measurementId: 'G-H8QK5LGE3X',
  );

}